@MMO_Idle.API_HostAddress = https://localhost:7043
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk2ZDdjMC1iYmZlLTdkM2UtYTBlZS1kMjk0NGVkZTQzNmQiLCJ1bmlxdWVfbmFtZSI6InRtMTk5NTAzIiwianRpIjoiYWZkYzQyMjYtOWM0ZC00MjdlLWE1NGQtOTYyMDFkNWQ1NjM1IiwiZXhwIjoyNTM0MDIyNzIwMDAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNDMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDQzIn0.ZbcMU5JtD4geoOdhqf-SjiJwVDqk9yqkVQGXVV5LtW0
@characterId = 0196d7dd-d664-7253-becb-7db0f2732498
### 登录
Post {{MMO_Idle.API_HostAddress}}/api/account/login
Accept: application/json
Content-Type: application/json

{
    "userName": "tm199503",
    "password": "12345678"
}

### 获取角色列表
GET {{MMO_Idle.API_HostAddress}}/api/character/list
Accept: application/json
Authorization: Bearer {{authToken}}

### 创建角色
Post {{MMO_Idle.API_HostAddress}}/api/character/add
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "characterName": "田蜜1号",
    "class": 1
}


### 获取角色全部状态
GET {{MMO_Idle.API_HostAddress}}/api/character/{{characterId}}/details
Accept: application/json
Authorization: Bearer {{authToken}}

### 获取角色装备信息
GET {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/equipment
Accept: application/json
Authorization: Bearer {{authToken}}
### 获取角色背包物品列表
GET {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/backpack
Accept: application/json
Authorization: Bearer {{authToken}}

### 穿戴装备
Post {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/equip/35
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 卸下装备
Post {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/unequip/35
Accept: application/json
Content-Type: application/json

### test signalR
Post {{MMO_Idle.API_HostAddress}}/api/testSignalr/ReceiveMessage
Accept: application/json
Content-Type: application/json

{
    "user": "jim96",
    "content": "1231456"
}
