@MMO_Idle.API_HostAddress = https://localhost:7043
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk2YjQyOC1jNzBkLTc1YzEtYjlmZi03YWNmNWFlZWNkMGMiLCJ1bmlxdWVfbmFtZSI6ImppbTk2IiwianRpIjoiNGJlZmQxMWItNTllMS00YTg2LTk4ZDktMjRlY2VkMTAwZjRiIiwiZXhwIjoxNzQ3MzI0MjE4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDQzIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA0MyJ9.lgSXf4khybWaXnL_9xIOMYAdRHwvnnGB87azqJWnUyw
@characterId = 278b9b5c-1852-45f7-8697-2363956a5240
### 登录
Post {{MMO_Idle.API_HostAddress}}/api/account/login
Accept: application/json
Content-Type: application/json

{
    "userName": "jim96",
    "password": "123456"
}

### 获取角色列表
GET {{MMO_Idle.API_HostAddress}}/api/account/characters
Accept: application/json
Authorization: Bearer {{authToken}}

### 创建角色
Post {{MMO_Idle.API_HostAddress}}/api/character/add
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "characterName": "吉姆",
    "class": 1
}


### 获取角色全部状态
GET {{MMO_Idle.API_HostAddress}}/api/character/{{characterId}}/details
Accept: application/json
Authorization: Bearer {{authToken}}

### 获取角色装备信息
GET {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/equipment
Accept: application/json
Authorization: Bearer {{authToken}}
### 获取角色背包物品列表
GET {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/backpack
Accept: application/json
Authorization: Bearer {{authToken}}

### 穿戴装备
Post {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/equip/35
Accept: application/json
Content-Type: application/json

### 卸下装备
Post {{MMO_Idle.API_HostAddress}}/api/characterEquipment/{{characterId}}/unequip/35
Accept: application/json
Content-Type: application/json

### 卸下装备
Post {{MMO_Idle.API_HostAddress}}/api/testSignalr/ReceiveMessage
Accept: application/json
Content-Type: application/json

{
    "user": "jim96",
    "content": "1231456"
}
